version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/phone"
    ports:
      - "8000:8000"
    depends_on:
      - db